### ISSUE TITLE
序言里需要hadley写什么？

### ISSUE THREAD

**Issue by yihui** [cosname/ggplot2-translation#1]
hadley大人说可以写，不过写啥呢？

**Comment by taiyun** [comment]
这这看人家了，想些啥就写啥，写啥都欢迎。我见过的套路类似是：我非常高兴地看见ggplot2在中国生根发芽、开枝散叶、开花结果之类的，或许再加一些赞誉之词。

**Comment by doctorjxd** [comment]
现在ggplot2的版本是 0.9.x，那么1.0.0版本的展望和趋势是怎样的呢？让hadley大人指点一下。
